services:
  web:
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN
    volumes:
      - ${DDEV_APPROOT}:${DDEV_APPROOT}
      - ~/.claude/:/home/${DDEV_USER}/.claude
      - ~/.claude.json:/home/${DDEV_USER}/.claude.json
      - ~/.config/basecamp-mcp/:/home/${DDEV_USER}/.config/basecamp-mcp/
      - ~/.codex/:/home/${DDEV_USER}/.codex
