services:
  web:
    environment:
        - GITHUB_PAT
        - JENKINS_AUTH
    volumes:
      - ~/acp/.codex/:/home/${DDEV_USER}/.codex/
      - ~/acp/.claude/:/home/${DDEV_USER}/.claude/
      - ~/acp/.claude.json:/home/${DDEV_USER}/.claude.json
      - ~/acp/.config/:/home/${DDEV_USER}/.config/
